// Automatically generated songs database
const songsData = {
  "cloud": [
    {
      "id": "cloud-106",
      "title": "Surah Quraish",
      "surahNo": 106,
      "url": "https://res.cloudinary.com/dnudhbjle/video/upload/q_auto/f_auto/v1781086630/106_-_Surat_Quraish_mbzdvo.mp3",
      "artist": "Idris Abkar",
      "album": "Cloud Recitations",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "isCloud": true
    },
    {
      "id": "cloud-112",
      "title": "Surah Al-Ikhlas",
      "surahNo": 112,
      "url": "https://res.cloudinary.com/dnudhbjle/video/upload/q_auto/f_auto/v1781086632/112_-_Surat_Al-Ikhlas_wlnjjt.mp3",
      "artist": "Idris Abkar",
      "album": "Cloud Recitations",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "isCloud": true
    },
    {
      "id": "cloud-113",
      "title": "Surah Al-Falaq",
      "surahNo": 113,
      "url": "https://res.cloudinary.com/dnudhbjle/video/upload/q_auto/f_auto/v1781086631/113_-_Surat_Al-Falaq_bku1w1.mp3",
      "artist": "Idris Abkar",
      "album": "Cloud Recitations",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "isCloud": true
    },
    {
      "id": "cloud-098",
      "title": "Surah Al-Bayyina",
      "surahNo": 98,
      "url": "https://res.cloudinary.com/dnudhbjle/video/upload/q_auto/f_auto/v1781086632/098_-_Surat_Al-Bayyina_ddcpsc.mp3",
      "artist": "Idris Abkar",
      "album": "Cloud Recitations",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "isCloud": true
    },
    {
      "id": "cloud-114",
      "title": "Surah An-Nas",
      "surahNo": 114,
      "url": "https://res.cloudinary.com/dnudhbjle/video/upload/q_auto/f_auto/v1781086631/114_-_Surat_An-Nas_pmuqyc.mp3",
      "artist": "Idris Abkar",
      "album": "Cloud Recitations",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "isCloud": true
    },
    {
      "id": "cloud-111",
      "title": "Surah Al-Masadd",
      "surahNo": 111,
      "url": "https://res.cloudinary.com/dnudhbjle/video/upload/q_auto/f_auto/v1781086631/111_-_Surat_Al-Masadd_oxeerv.mp3",
      "artist": "Idris Abkar",
      "album": "Cloud Recitations",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "isCloud": true
    }
  ],
  "local": [
    {
      "id": "local-1",
      "title": "Surah Al-Fatiha",
      "surahNo": 1,
      "url": "idris Abkar_Full/001 - Surah Al-Fatiha.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:44",
      "durationSec": 44.213,
      "isCloud": false
    },
    {
      "id": "local-2",
      "title": "Surah Al-Baqara",
      "surahNo": 2,
      "url": "idris Abkar_Full/002 - Surah Al-Baqara.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "117:14",
      "durationSec": 7034.069,
      "isCloud": false
    },
    {
      "id": "local-3",
      "title": "Surah Aal-E-Imran",
      "surahNo": 3,
      "url": "idris Abkar_Full/003 - Surah Aal-E-Imran.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "78:24",
      "durationSec": 4704.221,
      "isCloud": false
    },
    {
      "id": "local-4",
      "title": "Surah An-Nisa",
      "surahNo": 4,
      "url": "idris Abkar_Full/004 - Surah An-Nisa.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "84:15",
      "durationSec": 5055.149,
      "isCloud": false
    },
    {
      "id": "local-5",
      "title": "Surah Al-Maeda",
      "surahNo": 5,
      "url": "idris Abkar_Full/005 - Surah Al-Maeda.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "57:32",
      "durationSec": 3452.045,
      "isCloud": false
    },
    {
      "id": "local-6",
      "title": "Surah Al-Anaam",
      "surahNo": 6,
      "url": "idris Abkar_Full/006 - Surah Al-Anaam.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "67:39",
      "durationSec": 4059.893,
      "isCloud": false
    },
    {
      "id": "local-7",
      "title": "Surah Al-Araf",
      "surahNo": 7,
      "url": "idris Abkar_Full/007 - Surah Al-Araf.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "77:30",
      "durationSec": 4650.077,
      "isCloud": false
    },
    {
      "id": "local-8",
      "title": "Surah Al-Anfal",
      "surahNo": 8,
      "url": "idris Abkar_Full/008 - Surah Al-Anfal.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "30:36",
      "durationSec": 1836.7245,
      "isCloud": false
    },
    {
      "id": "local-9",
      "title": "Surah at Tawbah",
      "surahNo": 9,
      "url": "idris Abkar_Full/009 - Surah at Tawbah.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "64:36",
      "durationSec": 3876.130187,
      "isCloud": false
    },
    {
      "id": "local-10",
      "title": "Surah Yunus",
      "surahNo": 10,
      "url": "idris Abkar_Full/010 - Surah Yunus.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "38:11",
      "durationSec": 2291.9865,
      "isCloud": false
    },
    {
      "id": "local-11",
      "title": "Surah Hud",
      "surahNo": 11,
      "url": "idris Abkar_Full/011 - Surat Hud.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "38:20",
      "durationSec": 2300.021062,
      "isCloud": false
    },
    {
      "id": "local-12",
      "title": "Surah Yusuf",
      "surahNo": 12,
      "url": "idris Abkar_Full/012 - Surat Yusuf(1).mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "32:21",
      "durationSec": 1941.408,
      "isCloud": false
    },
    {
      "id": "local-13",
      "title": "Surah Ar-Rad",
      "surahNo": 13,
      "url": "idris Abkar_Full/013 - Surat Ar-Rad(1).mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "20:31",
      "durationSec": 1231.104,
      "isCloud": false
    },
    {
      "id": "local-14",
      "title": "Surah Ibrahim",
      "surahNo": 14,
      "url": "idris Abkar_Full/014 - Surat Ibrahim(1).mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "20:28",
      "durationSec": 1228.104,
      "isCloud": false
    },
    {
      "id": "local-15",
      "title": "Surah Al-Hijr",
      "surahNo": 15,
      "url": "idris Abkar_Full/015 - Surat Al-Hijr.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "17:50",
      "durationSec": 1070.736,
      "isCloud": false
    },
    {
      "id": "local-16",
      "title": "Surah An-Nahl",
      "surahNo": 16,
      "url": "idris Abkar_Full/016 - Surat An-Nahl.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "41:38",
      "durationSec": 2498.112,
      "isCloud": false
    },
    {
      "id": "local-17",
      "title": "Surah Al-Isra",
      "surahNo": 17,
      "url": "idris Abkar_Full/017 - Surat Al-Isra.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "36:58",
      "durationSec": 2218.109375,
      "isCloud": false
    },
    {
      "id": "local-18",
      "title": "Surah Al-Kahf",
      "surahNo": 18,
      "url": "idris Abkar_Full/018 - Surat Al-Kahf.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "36:58",
      "durationSec": 2218.109375,
      "isCloud": false
    },
    {
      "id": "local-19",
      "title": "Surah Maryam",
      "surahNo": 19,
      "url": "idris Abkar_Full/019 - Surat Maryam.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "22:21",
      "durationSec": 1341.264,
      "isCloud": false
    },
    {
      "id": "local-20",
      "title": "Surah Ta-Ha",
      "surahNo": 20,
      "url": "idris Abkar_Full/020 - Surat Ta-Ha(1).mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "30:15",
      "durationSec": 1815.384,
      "isCloud": false
    },
    {
      "id": "local-21",
      "title": "Surah Al-Anbiya",
      "surahNo": 21,
      "url": "idris Abkar_Full/021 - Surat Al-Anbiya.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "29:06",
      "durationSec": 1746.048,
      "isCloud": false
    },
    {
      "id": "local-22",
      "title": "Surah Al-Hajj",
      "surahNo": 22,
      "url": "idris Abkar_Full/022 - Surat Al-Hajj.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "28:18",
      "durationSec": 1698.432,
      "isCloud": false
    },
    {
      "id": "local-23",
      "title": "Surah Al-Mumenoon",
      "surahNo": 23,
      "url": "idris Abkar_Full/023 - Surat Al-Mumenoon.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "26:49",
      "durationSec": 1609.176,
      "isCloud": false
    },
    {
      "id": "local-24",
      "title": "Surah An-Noor",
      "surahNo": 24,
      "url": "idris Abkar_Full/024 - Surat An-Noor.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "31:07",
      "durationSec": 1867.584,
      "isCloud": false
    },
    {
      "id": "local-25",
      "title": "Surah Al-Furqan",
      "surahNo": 25,
      "url": "idris Abkar_Full/025 - Surat Al-Furqan.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "25:36",
      "durationSec": 1536.912,
      "isCloud": false
    },
    {
      "id": "local-26",
      "title": "Surah Ash-Shuara",
      "surahNo": 26,
      "url": "idris Abkar_Full/026 - Surat Ash-Shuara.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "30:26",
      "durationSec": 1826.977937,
      "isCloud": false
    },
    {
      "id": "local-27",
      "title": "Surah An-Naml",
      "surahNo": 27,
      "url": "idris Abkar_Full/027 - Surah An-Naml.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "31:28",
      "durationSec": 1888.653061,
      "isCloud": false
    },
    {
      "id": "local-28",
      "title": "Surah Al-Qasas",
      "surahNo": 28,
      "url": "idris Abkar_Full/028 - Surah Al-Qasas.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "28:01",
      "durationSec": 1681.005714,
      "isCloud": false
    },
    {
      "id": "local-29",
      "title": "Surah Al-Ankaboot",
      "surahNo": 29,
      "url": "idris Abkar_Full/029 - Surat Al-Ankaboot.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "23:10",
      "durationSec": 1390.32,
      "isCloud": false
    },
    {
      "id": "local-30",
      "title": "Surah Ar-Room",
      "surahNo": 30,
      "url": "idris Abkar_Full/030 - Surat Ar-Room.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "20:58",
      "durationSec": 1258.128,
      "isCloud": false
    },
    {
      "id": "local-31",
      "title": "Surah Luqman",
      "surahNo": 31,
      "url": "idris Abkar_Full/031 - Surat Luqman.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "12:24",
      "durationSec": 744.984,
      "isCloud": false
    },
    {
      "id": "local-32",
      "title": "Surah As Sajdah",
      "surahNo": 32,
      "url": "idris Abkar_Full/032 - Surah As Sajdah.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "7:27",
      "durationSec": 447.399184,
      "isCloud": false
    },
    {
      "id": "local-33",
      "title": "Surah Al Ahzab",
      "surahNo": 33,
      "url": "idris Abkar_Full/033 - Surat Al Ahzab.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "28:42",
      "durationSec": 1722.044082,
      "isCloud": false
    },
    {
      "id": "local-34",
      "title": "Surah Saba",
      "surahNo": 34,
      "url": "idris Abkar_Full/034 - Surat Saba.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "20:11",
      "durationSec": 1211.8465,
      "isCloud": false
    },
    {
      "id": "local-35",
      "title": "Surah Fatir",
      "surahNo": 35,
      "url": "idris Abkar_Full/035 - Surat Fatir.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "17:55",
      "durationSec": 1075.09551,
      "isCloud": false
    },
    {
      "id": "local-36",
      "title": "Surah Ya-Seen",
      "surahNo": 36,
      "url": "idris Abkar_Full/036 - Surat Ya-Seen.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "18:53",
      "durationSec": 1133.844875,
      "isCloud": false
    },
    {
      "id": "local-37",
      "title": "Surah As-Saaffat",
      "surahNo": 37,
      "url": "idris Abkar_Full/037 - Surat As-Saaffat.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "22:33",
      "durationSec": 1353.430188,
      "isCloud": false
    },
    {
      "id": "local-38",
      "title": "Surah Sad",
      "surahNo": 38,
      "url": "idris Abkar_Full/038 - Surat Sad.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "19:27",
      "durationSec": 1167.856312,
      "isCloud": false
    },
    {
      "id": "local-39",
      "title": "Surah Az-Zumar",
      "surahNo": 39,
      "url": "idris Abkar_Full/039 - Surat Az-Zumar.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "28:40",
      "durationSec": 1720.32,
      "isCloud": false
    },
    {
      "id": "local-40",
      "title": "Surah Ghafir",
      "surahNo": 40,
      "url": "idris Abkar_Full/040 - Surat Ghafir.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "28:40",
      "durationSec": 1720.056,
      "isCloud": false
    },
    {
      "id": "local-41",
      "title": "Surah Fussilat",
      "surahNo": 41,
      "url": "idris Abkar_Full/041 - Surat Fussilat.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "21:24",
      "durationSec": 1284.388563,
      "isCloud": false
    },
    {
      "id": "local-42",
      "title": "Surah Ash-Shura",
      "surahNo": 42,
      "url": "idris Abkar_Full/042 - Surat Ash-Shura.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "23:22",
      "durationSec": 1402.096312,
      "isCloud": false
    },
    {
      "id": "local-43",
      "title": "Surah Az-Zukhruf",
      "surahNo": 43,
      "url": "idris Abkar_Full/043 - Surat Az-Zukhruf.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "23:34",
      "durationSec": 1414.765688,
      "isCloud": false
    },
    {
      "id": "local-44",
      "title": "Surah Ad-Dukhan",
      "surahNo": 44,
      "url": "idris Abkar_Full/044 - Surat Ad-Dukhan.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "11:02",
      "durationSec": 662.491375,
      "isCloud": false
    },
    {
      "id": "local-45",
      "title": "Surah Al-Jathiyah",
      "surahNo": 45,
      "url": "idris Abkar_Full/045 - Surah Al-Jathiyah.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "9:11",
      "durationSec": 551.235918,
      "isCloud": false
    },
    {
      "id": "local-46",
      "title": "Surah Al-'Ahqaf",
      "surahNo": 46,
      "url": "idris Abkar_Full/046 - Surah Al-'Ahqaf.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "11:49",
      "durationSec": 709.929796,
      "isCloud": false
    },
    {
      "id": "local-47",
      "title": "Surah Muhammad",
      "surahNo": 47,
      "url": "idris Abkar_Full/047 - Surat Muhammad.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "13:02",
      "durationSec": 782.448,
      "isCloud": false
    },
    {
      "id": "local-48",
      "title": "Surah Al-Fath",
      "surahNo": 48,
      "url": "idris Abkar_Full/048 - Surat Al-Fath.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "12:58",
      "durationSec": 778.318367,
      "isCloud": false
    },
    {
      "id": "local-49",
      "title": "Surah Al-Hujurat",
      "surahNo": 49,
      "url": "idris Abkar_Full/049 - Surah Al-Hujurat.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "6:11",
      "durationSec": 371.252245,
      "isCloud": false
    },
    {
      "id": "local-50",
      "title": "Surah Qaf",
      "surahNo": 50,
      "url": "idris Abkar_Full/050 - Surat Qaf.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "9:39",
      "durationSec": 579.816,
      "isCloud": false
    },
    {
      "id": "local-51",
      "title": "Surah Adh-Dhariyat",
      "surahNo": 51,
      "url": "idris Abkar_Full/051 - Surat Adh-Dhariyat.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "8:37",
      "durationSec": 517.992,
      "isCloud": false
    },
    {
      "id": "local-52",
      "title": "Surah At-Tur",
      "surahNo": 52,
      "url": "idris Abkar_Full/052 - Surat At-Tur.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "7:07",
      "durationSec": 427.968,
      "isCloud": false
    },
    {
      "id": "local-53",
      "title": "Surah An-Najm",
      "surahNo": 53,
      "url": "idris Abkar_Full/053 - Surat An-Najm.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "8:10",
      "durationSec": 490.848,
      "isCloud": false
    },
    {
      "id": "local-54",
      "title": "Surah Al-Qamar",
      "surahNo": 54,
      "url": "idris Abkar_Full/054 - Surat Al-Qamar.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "7:47",
      "durationSec": 467.256,
      "isCloud": false
    },
    {
      "id": "local-55",
      "title": "Surah Ar-Rahman",
      "surahNo": 55,
      "url": "idris Abkar_Full/055 - Surat Ar-Rahman.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "10:07",
      "durationSec": 607.464,
      "isCloud": false
    },
    {
      "id": "local-56",
      "title": "Surah Al-Waqia",
      "surahNo": 56,
      "url": "idris Abkar_Full/056 - Surat Al-Waqia.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "10:45",
      "durationSec": 645.168,
      "isCloud": false
    },
    {
      "id": "local-57",
      "title": "Surah Al-Hadid",
      "surahNo": 57,
      "url": "idris Abkar_Full/057 - Surat Al-Hadid.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "13:11",
      "durationSec": 791.256,
      "isCloud": false
    },
    {
      "id": "local-58",
      "title": "Surah Al-Mujadila",
      "surahNo": 58,
      "url": "idris Abkar_Full/058 - Surah Al-Mujadila.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "12:16",
      "durationSec": 736.287347,
      "isCloud": false
    },
    {
      "id": "local-59",
      "title": "Surah Al-Hashr",
      "surahNo": 59,
      "url": "idris Abkar_Full/059 - Surah Al-Hashr.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "12:45",
      "durationSec": 765.074286,
      "isCloud": false
    },
    {
      "id": "local-60",
      "title": "Surah Al-Mumtahanah",
      "surahNo": 60,
      "url": "idris Abkar_Full/060 - Surah Al-Mumtahanah(1).mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "9:57",
      "durationSec": 597.080816,
      "isCloud": false
    },
    {
      "id": "local-61",
      "title": "Surah As-Saf",
      "surahNo": 61,
      "url": "idris Abkar_Full/061 - Surah As-Saf(1).mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "5:17",
      "durationSec": 317.257143,
      "isCloud": false
    },
    {
      "id": "local-62",
      "title": "Surah Al Jumuah",
      "surahNo": 62,
      "url": "idris Abkar_Full/062 - Surah Al Jumuah.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "4:09",
      "durationSec": 249.312653,
      "isCloud": false
    },
    {
      "id": "local-63",
      "title": "Surah Al-Munafiqun",
      "surahNo": 63,
      "url": "idris Abkar_Full/063 - Surah Al-Munafiqun.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "4:48",
      "durationSec": 288.287347,
      "isCloud": false
    },
    {
      "id": "local-64",
      "title": "Surah At-Taghabun",
      "surahNo": 64,
      "url": "idris Abkar_Full/064 - Surah At-Taghabun.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "5:38",
      "durationSec": 338.311837,
      "isCloud": false
    },
    {
      "id": "local-65",
      "title": "Surah At-Talaq",
      "surahNo": 65,
      "url": "idris Abkar_Full/065 - Surah At-Talaq.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "7:37",
      "durationSec": 457.508571,
      "isCloud": false
    },
    {
      "id": "local-66",
      "title": "Surah At-Tahrim",
      "surahNo": 66,
      "url": "idris Abkar_Full/066 - Surah At-Tahrim.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "7:26",
      "durationSec": 446.302041,
      "isCloud": false
    },
    {
      "id": "local-67",
      "title": "Surah Al-Mulk",
      "surahNo": 67,
      "url": "idris Abkar_Full/067 - Surat Al-Mulk.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "6:24",
      "durationSec": 384.888,
      "isCloud": false
    },
    {
      "id": "local-68",
      "title": "Surah Al-Qalam",
      "surahNo": 68,
      "url": "idris Abkar_Full/068 - Surat Al-Qalam.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "6:23",
      "durationSec": 383.085688,
      "isCloud": false
    },
    {
      "id": "local-69",
      "title": "Surah Al-Haaqqa",
      "surahNo": 69,
      "url": "idris Abkar_Full/069 - Surat Al-Haaqqa.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "6:24",
      "durationSec": 384.816,
      "isCloud": false
    },
    {
      "id": "local-70",
      "title": "Surah Al-Maarij",
      "surahNo": 70,
      "url": "idris Abkar_Full/070 - Surat Al-Maarij.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "6:11",
      "durationSec": 371.88,
      "isCloud": false
    },
    {
      "id": "local-71",
      "title": "Surah Nooh",
      "surahNo": 71,
      "url": "idris Abkar_Full/071 - Surat Nooh.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "4:43",
      "durationSec": 283.152,
      "isCloud": false
    },
    {
      "id": "local-72",
      "title": "Surah Al-Jinn",
      "surahNo": 72,
      "url": "idris Abkar_Full/072 - Surat Al-Jinn.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "5:44",
      "durationSec": 344.448,
      "isCloud": false
    },
    {
      "id": "local-73",
      "title": "Surah Al-Muzzammil",
      "surahNo": 73,
      "url": "idris Abkar_Full/073 - Surat Al-Muzzammil.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "5:12",
      "durationSec": 312.696,
      "isCloud": false
    },
    {
      "id": "local-74",
      "title": "Surah Al-Muddaththir",
      "surahNo": 74,
      "url": "idris Abkar_Full/074 - Surat Al-Muddaththir.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "5:55",
      "durationSec": 355.968,
      "isCloud": false
    },
    {
      "id": "local-75",
      "title": "Surah Al-Qiyama",
      "surahNo": 75,
      "url": "idris Abkar_Full/075 - Surat Al-Qiyama.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "6:43",
      "durationSec": 403.608,
      "isCloud": false
    },
    {
      "id": "local-76",
      "title": "Surah Al-Insan",
      "surahNo": 76,
      "url": "idris Abkar_Full/076 - Surat Al-Insan(1).mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "7:30",
      "durationSec": 450.864,
      "isCloud": false
    },
    {
      "id": "local-77",
      "title": "Surah Al-Mursalat",
      "surahNo": 77,
      "url": "idris Abkar_Full/077 - Surat Al-Mursalat.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "4:23",
      "durationSec": 263.064,
      "isCloud": false
    },
    {
      "id": "local-78",
      "title": "Surah An-Naba",
      "surahNo": 78,
      "url": "idris Abkar_Full/078 - Surah An-Naba.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "3:40",
      "durationSec": 220.464,
      "isCloud": false
    },
    {
      "id": "local-79",
      "title": "Surah An-Naziat",
      "surahNo": 79,
      "url": "idris Abkar_Full/079 - Surat An-Naziat.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "3:24",
      "durationSec": 204.864,
      "isCloud": false
    },
    {
      "id": "local-80",
      "title": "Surah Abasa",
      "surahNo": 80,
      "url": "idris Abkar_Full/080 - Surah Abasa.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "2:45",
      "durationSec": 165.384,
      "isCloud": false
    },
    {
      "id": "local-81",
      "title": "Surah At-Takwir",
      "surahNo": 81,
      "url": "idris Abkar_Full/081 - Surah At-Takwir.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:55",
      "durationSec": 115.722437,
      "isCloud": false
    },
    {
      "id": "local-82",
      "title": "Surah Al-Infitar",
      "surahNo": 82,
      "url": "idris Abkar_Full/082 - Surah Al-Infitar.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:26",
      "durationSec": 86.909375,
      "isCloud": false
    },
    {
      "id": "local-83",
      "title": "Surah Al-Mutaffifin",
      "surahNo": 83,
      "url": "idris Abkar_Full/083 - Surah Al-Mutaffifin.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "3:15",
      "durationSec": 195.108563,
      "isCloud": false
    },
    {
      "id": "local-84",
      "title": "Surah Al-Inshiqaq",
      "surahNo": 84,
      "url": "idris Abkar_Full/084 - Surat Al-Inshiqaq.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:59",
      "durationSec": 119.7975,
      "isCloud": false
    },
    {
      "id": "local-85",
      "title": "Surah Al-Burooj",
      "surahNo": 85,
      "url": "idris Abkar_Full/085 - Surat Al-Burooj.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "2:01",
      "durationSec": 121.678312,
      "isCloud": false
    },
    {
      "id": "local-86",
      "title": "Surah At-Tariq",
      "surahNo": 86,
      "url": "idris Abkar_Full/086 - Surat At-Tariq.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:12",
      "durationSec": 72.777125,
      "isCloud": false
    },
    {
      "id": "local-87",
      "title": "Surah Al-Ala",
      "surahNo": 87,
      "url": "idris Abkar_Full/087 - Surat Al-Ala.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:23",
      "durationSec": 83.617937,
      "isCloud": false
    },
    {
      "id": "local-88",
      "title": "Surah Al-Ghashiya",
      "surahNo": 88,
      "url": "idris Abkar_Full/088 - Surat Al-Ghashiya.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:43",
      "durationSec": 103.68,
      "isCloud": false
    },
    {
      "id": "local-89",
      "title": "Surah Al-Fajr",
      "surahNo": 89,
      "url": "idris Abkar_Full/089 - Surat Al-Fajr.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "2:36",
      "durationSec": 156.10775,
      "isCloud": false
    },
    {
      "id": "local-90",
      "title": "Surah Al-Balad",
      "surahNo": 90,
      "url": "idris Abkar_Full/090 - Surat Al-Balad.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:27",
      "durationSec": 87.95425,
      "isCloud": false
    },
    {
      "id": "local-91",
      "title": "Surah Ash-Shams",
      "surahNo": 91,
      "url": "idris Abkar_Full/091 - Surat Ash-Shams.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:05",
      "durationSec": 65.306062,
      "isCloud": false
    },
    {
      "id": "local-92",
      "title": "Surah Al-Lail",
      "surahNo": 92,
      "url": "idris Abkar_Full/092 - Surat Al-Lail.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:31",
      "durationSec": 91.088938,
      "isCloud": false
    },
    {
      "id": "local-93",
      "title": "Surah Ad-Dhuha",
      "surahNo": 93,
      "url": "idris Abkar_Full/093 - Surat Ad-Dhuha.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:52",
      "durationSec": 52.532187,
      "isCloud": false
    },
    {
      "id": "local-94",
      "title": "Surah Al-Inshirah",
      "surahNo": 94,
      "url": "idris Abkar_Full/094 - Surat Al-Inshirah.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:31",
      "durationSec": 31.869375,
      "isCloud": false
    },
    {
      "id": "local-95",
      "title": "Surah At-Tin",
      "surahNo": 95,
      "url": "idris Abkar_Full/095 - Surat At-Tin.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:43",
      "durationSec": 43.572187,
      "isCloud": false
    },
    {
      "id": "local-96",
      "title": "Surah Al-Alaq",
      "surahNo": 96,
      "url": "idris Abkar_Full/096 - Surat Al-Alaq.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:22",
      "durationSec": 82.83425,
      "isCloud": false
    },
    {
      "id": "local-97",
      "title": "Surah Al-Qadr",
      "surahNo": 97,
      "url": "idris Abkar_Full/097 - Surat Al-Qadr.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:32",
      "durationSec": 32.992625,
      "isCloud": false
    },
    {
      "id": "local-98",
      "title": "Surah Al-Bayyina",
      "surahNo": 98,
      "url": "idris Abkar_Full/098 - Surat Al-Bayyina.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "1:48",
      "durationSec": 108.43425,
      "isCloud": false
    },
    {
      "id": "local-99",
      "title": "Surah Az-Zalzala",
      "surahNo": 99,
      "url": "idris Abkar_Full/099 - Surat Az-Zalzala.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:49",
      "durationSec": 49.76325,
      "isCloud": false
    },
    {
      "id": "local-100",
      "title": "Surah Al-Adiyat",
      "surahNo": 100,
      "url": "idris Abkar_Full/100 - Surat Al-Adiyat.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:52",
      "durationSec": 52.088125,
      "isCloud": false
    },
    {
      "id": "local-101",
      "title": "Surah Al-Qaria",
      "surahNo": 101,
      "url": "idris Abkar_Full/101 - Surat Al-Qaria.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:45",
      "durationSec": 45.035063,
      "isCloud": false
    },
    {
      "id": "local-102",
      "title": "Surah At-Takathur",
      "surahNo": 102,
      "url": "idris Abkar_Full/102 - Surat At-Takathur.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:38",
      "durationSec": 38.34775,
      "isCloud": false
    },
    {
      "id": "local-103",
      "title": "Surah Al-Asr",
      "surahNo": 103,
      "url": "idris Abkar_Full/103 - Surat Al-Asr.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:19",
      "durationSec": 19.487313,
      "isCloud": false
    },
    {
      "id": "local-104",
      "title": "Surah Al-Humaza",
      "surahNo": 104,
      "url": "idris Abkar_Full/104 - Surat Al-Humaza.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:42",
      "durationSec": 42.971375,
      "isCloud": false
    },
    {
      "id": "local-105",
      "title": "Surah Al-Fil",
      "surahNo": 105,
      "url": "idris Abkar_Full/105 - Surat Al-Fil.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:29",
      "durationSec": 29.596687,
      "isCloud": false
    },
    {
      "id": "local-106",
      "title": "Surah Quraish",
      "surahNo": 106,
      "url": "idris Abkar_Full/106 - Surat Quraish.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:26",
      "durationSec": 26.540375,
      "isCloud": false
    },
    {
      "id": "local-107",
      "title": "Surah Al-Maun",
      "surahNo": 107,
      "url": "idris Abkar_Full/107 - Surat Al-Maun.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:33",
      "durationSec": 33.332188,
      "isCloud": false
    },
    {
      "id": "local-108",
      "title": "Surah Al-Kauther",
      "surahNo": 108,
      "url": "idris Abkar_Full/108 - Surat Al-Kauther.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:17",
      "durationSec": 17.057938,
      "isCloud": false
    },
    {
      "id": "local-109",
      "title": "Surah Al-Kafiroon",
      "surahNo": 109,
      "url": "idris Abkar_Full/109 - Surat Al-Kafiroon.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:36",
      "durationSec": 36.493063,
      "isCloud": false
    },
    {
      "id": "local-110",
      "title": "Surah An-Nasr",
      "surahNo": 110,
      "url": "idris Abkar_Full/110 - Surat An-Nasr.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:31",
      "durationSec": 31.033438,
      "isCloud": false
    },
    {
      "id": "local-111",
      "title": "Surah Al-Masadd",
      "surahNo": 111,
      "url": "idris Abkar_Full/111 - Surat Al-Masadd.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:30",
      "durationSec": 30.72,
      "isCloud": false
    },
    {
      "id": "local-112",
      "title": "Surah Al-Ikhlas",
      "surahNo": 112,
      "url": "idris Abkar_Full/112 - Surat Al-Ikhlas.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:15",
      "durationSec": 15.177125,
      "isCloud": false
    },
    {
      "id": "local-113",
      "title": "Surah Al-Falaq",
      "surahNo": 113,
      "url": "idris Abkar_Full/113 - Surat Al-Falaq.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:24",
      "durationSec": 24.737938,
      "isCloud": false
    },
    {
      "id": "local-114",
      "title": "Surah An-Nas",
      "surahNo": 114,
      "url": "idris Abkar_Full/114 - Surat An-Nas.mp3",
      "artist": "Idris Abkar",
      "album": "Full Quran Recitation",
      "cover": "idris Abkar_Full/idrees-abkar-banner.jpg",
      "duration": "0:30",
      "durationSec": 30.014688,
      "isCloud": false
    }
  ]
};
